baseURL: "https://cagatayturkan.com/blog"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true
title: "Çağatay Türkan"
theme: "Niello-master"

languages:
  en:
    languageCode: "en-us"
    LanguageName: "🇺🇸EN"
    contentDir: "content/en"
    weight: 1
    menu:
      main:
        - name: "Home"
          url: "/blog/en/"
          weight: 1
        - name: "Categories"
          url: "/blog/en/categories/"
          weight: 2
        - name: "Tags"
          url: "/blog/en/tags/"
          weight: 3
        - name: "About"
          url: "/blog/en/about/"
          weight: 4
  tr:
    languageCode: "tr"
    LanguageName: "🇹🇷TR"
    contentDir: "content/tr"
    weight: 2
    menu:
      main:
        - name: "Ana Sayfa"
          url: "/blog/tr/"
          weight: 1
        - name: "Kategoriler"
          url: "/blog/tr/categories/"
          weight: 2
        - name: "Etiketler"
          url: "/blog/tr/tags/"
          weight: 3
        - name: "Hakkımda"
          url: "/blog/tr/about/"
          weight: 4

# Niello theme settings
params:
  description: "Personal blog of Çağatay Türkan"
  author: "Çağatay Türkan"
  mainSections: ["blog"]
  dateFormat: "January 2, 2006"
  comments: false
  images: []
  homeText: "Welcome to my blog"
  bannershowcase:
    limit: 5

outputs:
  home: ["HTML", "JSON"]

menu:
  main:
    - name: "Home"
      url: "/blog/en/"
      weight: 1
    - name: "About"
      url: "/blog/en/about/"
      weight: 2
    - name: "Blog-EN"
      url: "/blog/en/blog/"
      weight: 4
    - name: "Blog-TR"
      url: "/blog/tr/blog/"
      weight: 5

permalinks:
  blog: /:section/:filename/ 