baseURL: "https://cagatayturkan.com/blog"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true
title: "Çağatay Türkan"
theme: "Niello-master"

languages:
  en:
    languageCode: "en-us"
    LanguageName: "🇺🇸EN"
    contentDir: "content/en"
    weight: 1
    menu:
      main:
        - name: "Home"
          url: "/en/"
          weight: 1
        - name: "Categories"
          url: "/en/categories/"
          weight: 2
        - name: "Tags"
          url: "/en/tags/"
          weight: 3
        - name: "About"
          url: "/en/about/"
          weight: 4
  tr:
    languageCode: "tr"
    LanguageName: "🇹🇷TR"
    contentDir: "content/tr"
    weight: 2
    menu:
      main:
        - name: "Ana Sayfa"
          url: "/tr/"
          weight: 1
        - name: "Kategoriler"
          url: "/tr/categories/"
          weight: 2
        - name: "Etiketler"
          url: "/tr/tags/"
          weight: 3
        - name: "Hakkımda"
          url: "/tr/about/"
          weight: 4

# Niello theme settings
params:
  description: "Personal blog of Çağatay Türkan"
  author: "Çağatay Türkan"
  mainSections: [""]
  dateFormat: "January 2, 2006"
  comments: false
  images: []
  homeText: "Welcome to my blog"
  bannershowcase:
    limit: 5

outputs:
  home: ["HTML", "JSON"]

permalinks:
  blog: /:section/:filename/ 