baseURL = "/" 
languageCode = "en-us"
title = "Çağatay Türkan"
theme = "qubt"
DefaultContentLanguage = "en"



[params]
    project_display_limit = 4
    preserveTaxonomyNames = true
    sitemap_priority = "0.75"
    paginate = 13
    [[params.links]]
    github = "https://github.com/cagatayturkann"
    linkedin = "https://www.linkedin.com/in/cagatayturkann/"
    x-twitter = "https://twitter.com/cagatayturkann"
    facebook= "https://facebook.com/cagatayturkann"
    instagram= "https://instagram.com/cagatayturkann"
    
[params.author]
    name = "Çağatay Türkan"
    image = "/images/author.jpeg"
    greeting = "A personal blog for Computer Engineer :computer:"
    icon = ":wave:"    
    

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2    

#[[menu.main]]
    #name = "Projects"
    #url = "/projects"
    #weight = 3

[[menu.main]]
    name = "Blog-EN"
    url = "/blog-en"
    weight = 4

[[menu.main]]
    name = "Blog-TR"
    url = "/blog-tr"
    weight = 5

