baseURL = "https://cagatayturkann.github.ip" 
languageCode = "en-us"
title = "Çağatay Türkan | Blog"
theme = "qubt"
DefaultContentLanguage = "en"



[params]
    project_display_limit = 4
    preserveTaxonomyNames = true
    sitemap_priority = "0.75"
    paginate = 12
    [[params.links]]
    github = "https://github.com/cagatayturkann"
    linkedin = "https://www.linkedin.com/in/cagatayturkann/"
    x-twitter = "https://twitter.com/cagatayturkann"
    facebook= "https://facebook.com/cagatayturkann"
    instagram= "https://instagram.com/cagatayturkann"
    
[params.author]
    name = "Qubt"
    image = "author.jpeg"
    greeting = "A personal blog theme for Hugo :evergreen_tree:"
    icon = ":wave:"    
    

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2    

[[menu.main]]
    name = "Projects"
    url = "/project"
    weight = 3

[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 4


