name: Deploy to cagatayturkan.github.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Blog Repository
        uses: actions/checkout@v2
        with:
          repository: 'cagatayturkann/blog'  # 'username' kısmını kendi GitHub kullanıcı adınız ile değiştirin
          path: 'blog'  # Blog deposunu 'blog' dizinine çıkartT

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "çağatay" "${{ secrets.deploy_key }}"
          echo "çaça" "${{ secrets.DEPLOY_TOKEN }}"
          echo "${{ secrets.deploy_key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Deploy to cagatayturkan.github.io
        run: |
          cd blog/public  # Bu adım, "blog/public" dizinine geçiş yapar
          git config --global user.email "cagatayturkann@gmail.com"
          git config --global user.name "Çağatay Türkan"
          git init
          git add .
          git commit -m "Deploy to cagatayturkan.github.io"
          git push --force "git@github.com:cagatayturkann/cagatayturkan.github.io.git" master
