name: Deploy to cagatayturkan.github.io

on:
  push:
    branches:
      - main  # Burada hangi branch'e push yapılınca çalışacağını ayarlayabilirsiniz.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Blog Repository
      uses: actions/checkout@v2
      with:
        repository: 'cagatayturkann/blog'  # 'username' kısmını kendi GitHub kullanıcı adınız ile değiştirin
        
    - name: Set up SSH
      run: | 
        mkdir -p ~/.ssh/
        echo "${{ secrets.deploy_token }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

   
    - name: Deploy to cagatayturkan.github.io
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.deploy_token }}  # Önceden oluşturduğunuz GitHub Access Token'ı burada kullanın.
        external_repository: 'username/cagatayturkan.github.io'
        publish_branch: 'master'  # 'cagatayturkan.github.io' reposunun hangi branch'ine deploy edileceğini belirtin
        publish_dir: './public'
